export enum DataType {
  VFXItemData = 'VFXItemData',

  // Assets
  Material = 'Material',
  Shader = 'Shader',
  Geometry = 'Geometry',
  Texture = 'Texture',
  Image = 'Image',
  AnimationClip = 'AnimationClip',
  BinaryAsset = 'BinaryAsset',
  Sprite = 'Sprite',

  // Timeline
  TrackAsset = 'TrackAsset',
  TimelineAsset = 'TimelineAsset',
  ObjectBindingTrack = 'ObjectBindingTrack',
  TransformTrack = 'TransformTrack',
  SpriteColorTrack = 'SpriteColorTrack',
  ActivationTrack = 'ActivationTrack',
  SubCompositionTrack = 'SubCompositionTrack',
  FloatPropertyTrack = 'FloatPropertyTrack',
  ColorPropertyTrack = 'ColorPropertyTrack',
  Vector2PropertyTrack = 'Vector2PropertyTrack',
  Vector3PropertyTrack = 'Vector3PropertyTrack',
  Vector4PropertyTrack = 'Vector4PropertyTrack',
  SpritePropertyTrack = 'SpritePropertyTrack',

  TransformPlayableAsset = 'TransformPlayableAsset',
  SpriteColorPlayableAsset = 'SpriteColorPlayableAsset',
  ActivationPlayableAsset = 'ActivationPlayableAsset',
  SubCompositionPlayableAsset = 'SubCompositionPlayableAsset',
  FloatPropertyPlayableAsset = 'FloatPropertyPlayableAsset',
  ColorPropertyPlayableAsset = 'ColorPropertyPlayableAsset',
  Vector2PropertyPlayableAsset = 'Vector2PropertyPlayableAsset',
  Vector3PropertyPlayableAsset = 'Vector3PropertyPlayableAsset',
  Vector4PropertyPlayableAsset = 'Vector4PropertyPlayableAsset',
  SpritePropertyPlayableAsset = 'SpritePropertyPlayableAsset',

  // Components
  MeshComponent = 'MeshComponent',
  SkyboxComponent = 'SkyboxComponent',
  LightComponent = 'LightComponent',
  CameraComponent = 'CameraComponent',
  ModelPluginComponent = 'ModelPluginComponent',
  TreeComponent = 'TreeComponent',
  AnimationComponent = 'AnimationComponent',
  SpineComponent = 'SpineComponent',
  VideoComponent = 'VideoComponent',
  AudioComponent = 'AudioComponent',
  RichTextComponent = 'RichTextComponent',
  OrientationComponent = 'OrientationComponent',
  ShapeComponent = 'ShapeComponent',
  SpriteComponent = 'SpriteComponent',
  ParticleSystem = 'ParticleSystem',
  InteractComponent = 'InteractComponent',
  CameraController = 'CameraController',
  PostProcessVolume = 'PostProcessVolume',
  EffectComponent = 'EffectComponent',
  TextComponent = 'TextComponent',
  AnimationGraphAsset = 'AnimationGraphAsset',
  CompositionComponent = 'CompositionComponent',
  FFDComponent = 'FFDComponent',
  FrameComponent = 'FrameComponent',
  Animator = 'Animator',
  DomContentComponent = 'DomContentComponent',
  UIControl = 'UIControl',

  // GUI Controls
  Control = 'Control',
  Container = 'Container',
  HBoxContainer = 'HBoxContainer',
  VBoxContainer = 'VBoxContainer',
  GridContainer = 'GridContainer',
  PanelContainer = 'PanelContainer',
  MarginContainer = 'MarginContainer',
  CenterContainer = 'CenterContainer',
  AspectRatioContainer = 'AspectRatioContainer',
  ScrollContainer = 'ScrollContainer',
  HScrollBar = 'HScrollBar',
  VScrollBar = 'VScrollBar',
  HSeparator = 'HSeparator',
  VSeparator = 'VSeparator',
  Label = 'Label',
  LineEdit = 'LineEdit',
  TextEdit = 'TextEdit',
  PopupPanel = 'PopupPanel',
  PopupMenu = 'PopupMenu',
  MenuButton = 'MenuButton',
  OptionButton = 'OptionButton',
  ColorPicker = 'ColorPicker',
  ColorPickerButton = 'ColorPickerButton',
  TextureRect = 'TextureRect',
  NinePatchRect = 'NinePatchRect',
  ColorRect = 'ColorRect',
  Panel = 'Panel',
  ProgressBar = 'ProgressBar',
  Button = 'Button',
  Checkbox = 'Checkbox',
  CheckButton = 'CheckButton',
  HSlider = 'HSlider',
  VSlider = 'VSlider',

  // Non-EffectObject
  TimelineClip = 'TimelineClip',
}
