export enum DataType {
  VFXItemData = 'VFXItemData',

  // Assets
  Material = 'Material',
  Shader = 'Shader',
  Geometry = 'Geometry',
  Texture = 'Texture',
  Image = 'Image',
  AnimationClip = 'AnimationClip',
  BinaryAsset = 'BinaryAsset',

  // Timeline
  TrackAsset = 'TrackAsset',
  TimelineAsset = 'TimelineAsset',
  ObjectBindingTrack = 'ObjectBindingTrack',
  TransformTrack = 'TransformTrack',
  SpriteColorTrack = 'SpriteColorTrack',
  ActivationTrack = 'ActivationTrack',
  SubCompositionTrack = 'SubCompositionTrack',
  FloatPropertyTrack = 'FloatPropertyTrack',
  ColorPropertyTrack = 'ColorPropertyTrack',
  Vector2PropertyTrack = 'Vector2PropertyTrack',
  Vector4PropertyTrack = 'Vector4PropertyTrack',

  TransformPlayableAsset = 'TransformPlayableAsset',
  SpriteColorPlayableAsset = 'SpriteColorPlayableAsset',
  ActivationPlayableAsset = 'ActivationPlayableAsset',
  SubCompositionPlayableAsset = 'SubCompositionPlayableAsset',
  FloatPropertyPlayableAsset = 'FloatPropertyPlayableAsset',
  ColorPropertyPlayableAsset = 'ColorPropertyPlayableAsset',
  Vector2PropertyPlayableAsset = 'Vector2PropertyPlayableAsset',
  Vector4PropertyPlayableAsset = 'Vector4PropertyPlayableAsset',

  // Components
  MeshComponent = 'MeshComponent',
  SkyboxComponent = 'SkyboxComponent',
  LightComponent = 'LightComponent',
  CameraComponent = 'CameraComponent',
  ModelPluginComponent = 'ModelPluginComponent',
  TreeComponent = 'TreeComponent',
  AnimationComponent = 'AnimationComponent',
  SpineComponent = 'SpineComponent',
  VideoComponent = 'VideoComponent',
  AudioComponent = 'AudioComponent',
  RichTextComponent = 'RichTextComponent',
  OrientationComponent = 'OrientationComponent',
  ShapeComponent = 'ShapeComponent',
  SpriteComponent = 'SpriteComponent',
  ParticleSystem = 'ParticleSystem',
  InteractComponent = 'InteractComponent',
  CameraController = 'CameraController',
  PostProcessVolume = 'PostProcessVolume',
  EffectComponent = 'EffectComponent',
  TextComponent = 'TextComponent',
  AnimationGraphAsset = 'AnimationGraphAsset',
  CompositionComponent = 'CompositionComponent',
  FFDComponent = 'FFDComponent',
  Animator = 'Animator',
  FFDComponent = 'FFDComponent',
  // Non-EffectObject
  TimelineClip = 'TimelineClip',
}
